version: "3"
services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: "gin"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - gin-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  gin-mysql:
    driver: local
